# Generated by Django 3.0.8 on 2021-10-25 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User_story',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actor', models.CharField(default='Quien', max_length=200, verbose_name='Actor')),
                ('accion', models.CharField(default='Que', max_length=500, verbose_name='Accion')),
                ('proposito', models.CharField(default='Para que', max_length=500, verbose_name='Proposito')),
                ('dificultad', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Historia de Usuario',
                'verbose_name_plural': 'Historias de Usuario',
                'db_table': 'historia',
                'ordering': ['id'],
            },
        ),
    ]
