# Generated by Django 3.0.8 on 2021-11-23 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Auxiliar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cuento', models.CharField(default='Historia de Usuario', max_length=1000, verbose_name='Historia')),
            ],
            options={
                'verbose_name': 'Relatos',
                'db_table': 'cuento',
                'ordering': ['id'],
            },
        ),
    ]
