# Generated by Django 3.0.8 on 2021-11-25 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0003_auto_20211123_1228'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auxiliar',
            name='relatoUsuario',
            field=models.CharField(max_length=1000, verbose_name='Historia'),
        ),
    ]
