# Generated by Django 3.0.8 on 2021-12-08 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0004_auto_20211125_1056'),
    ]

    operations = [
        migrations.CreateModel(
            name='Accion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actor', models.CharField(max_length=300, verbose_name='Actor')),
                ('que', models.CharField(max_length=1000, verbose_name='Que')),
                ('para_que', models.CharField(max_length=1000, verbose_name='Para_que')),
                ('posicion', models.PositiveIntegerField()),
            ],
            options={
                'verbose_name': 'Accion',
                'verbose_name_plural': 'Acciones',
                'db_table': 'accion',
                'ordering': ['id'],
            },
        ),
        migrations.AlterModelOptions(
            name='auxiliar',
            options={'ordering': ['id'], 'verbose_name': 'Relato del Usuario', 'verbose_name_plural': 'Relatos'},
        ),
    ]
